### ISSUE TITLE
Support for Scala 2.12

### ISSUE THREAD

**Issue by leandrob13** [dragos/dragos-vscode-scala#38]
I tried updating scala on this project and publishing locally and the error is the same. It seems a problem with scala compiler versions but I don't know where to look besides updating dependencies and scalaVersion.

```
[2017-04-20 13:55:39,966] ERROR akka.actor.OneForOneStrategy - scala.tools.nsc.transform.Transform.$init$(Lscala/tools/nsc/transform/Transform;)V
akka.actor.ActorInitializationException: akka://ENSIME/user/server/ensimeProject/project/scalac: exception during creation
	at akka.actor.ActorInitializationException$.apply(Actor.scala:175)
	at akka.actor.ActorCell.create(ActorCell.scala:607)
	at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:461)
	at akka.actor.ActorCell.systemInvoke(ActorCell.scala:483)
	at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala:282)
	at akka.dispatch.Mailbox.run(Mailbox.scala:223)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at scala.tools.nsc.plugins.Plugin$.instantiate(Plugin.scala:192)
	at scala.tools.nsc.plugins.Plugins$$anonfun$loadRoughPluginsList$2.apply(Plugins.scala:47)
	at scala.tools.nsc.plugins.Plugins$$anonfun$loadRoughPluginsList$2.apply(Plugins.scala:47)
	at scala.collection.immutable.List.map(List.scala:273)
	at scala.tools.nsc.plugins.Plugins$class.loadRoughPluginsList(Plugins.scala:47)
	at scala.tools.nsc.Global.loadRoughPluginsList(Global.scala:39)
	at scala.tools.nsc.plugins.Plugins$class.roughPluginsList(Plugins.scala:50)
	at scala.tools.nsc.Global.roughPluginsList$lzycompute(Global.scala:39)
	at scala.tools.nsc.Global.roughPluginsList(Global.scala:39)
	at scala.tools.nsc.plugins.Plugins$class.loadPlugins(Plugins.scala:86)
	at scala.tools.nsc.Global.loadPlugins(Global.scala:39)
	at scala.tools.nsc.plugins.Plugins$class.plugins(Plugins.scala:102)
	at scala.tools.nsc.Global.plugins$lzycompute(Global.scala:39)
	at scala.tools.nsc.Global.plugins(Global.scala:39)
	at scala.tools.nsc.plugins.Plugins$class.computePluginPhases(Plugins.scala:113)
	at scala.tools.nsc.Global.computePluginPhases(Global.scala:39)
	at scala.tools.nsc.Global.computePhaseDescriptors(Global.scala:750)
	at scala.tools.nsc.Global.phaseDescriptors$lzycompute(Global.scala:755)
	at scala.tools.nsc.Global.phaseDescriptors(Global.scala:755)
	at scala.tools.nsc.Global$Run.<init>(Global.scala:1237)
	at scala.tools.nsc.interactive.Global$TyperRun.<init>(Global.scala:1320)
	at scala.tools.nsc.interactive.Global.newTyperRun(Global.scala:1343)
	at scala.tools.nsc.interactive.Global.<init>(Global.scala:299)
	at org.ensime.core.RichPresentationCompiler.<init>(RichPresentationCompiler.scala:377)
	at org.ensime.core.Analyzer.makeScalaCompiler(Analyzer.scala:108)
	at org.ensime.core.Analyzer.preStart(Analyzer.scala:100)
	at akka.actor.Actor$class.aroundPreStart(Actor.scala:505)
	at org.ensime.core.Analyzer.aroundPreStart(Analyzer.scala:53)
	at akka.actor.ActorCell.create(ActorCell.scala:590)
	... 9 common frames omitted
Caused by: java.lang.NoSuchMethodError: scala.tools.nsc.transform.Transform.$init$(Lscala/tools/nsc/transform/Transform;)V
```

**Comment by dragos** [comment]
Indeed! I'm not sure Ensime works with Scala 2.12, or if you need to do something special for that...

**Comment by leandrob13** [comment]
@dragos I managed to get atom-ensime to work with the server 2.0.0-SNAPSHOT. It still presents some errors but the server starts without this exception. That it why I thought it might be something that still depends on scala 2.11 in vscode-ensime. I wish I could help you with this but honestly I ran out of ideas.

**Comment by dragos** [comment]
Ah, you're absolutely right. We don't cross-compile so this plugin is only for Scala 2.11. There should be a way to fix this though, thanks for reporting

**Comment by jvican** [comment]
Oh, now that we have a fast 2.12.x series, it would be lovely to have this cross-compiled :smile:.

**Comment by dragos** [comment]
Absolutely... we need a bit of logic in the client as well, I think.

**Comment by dragos** [comment]
The thin client (currently written in typescript) would need to know what version is the project in order to launch the correct version of the LSP. The simplest solution would be to make that a setting, or alternatively parse the ensime configuration to extract the Scala version. That would be easier if our client was in Scala.js, as we might be able to share the code reading ensime config files.

**Comment by Blaisorblade** [comment]
Question: is this still an issue? Ignorant me just did the obvious thing with SBT 1.0.2 and sbt-ensime 2.0.1, and a few things work with Scala 2.12.3. If this is an issue, then maybe I should retest with Scala 2.11.

I do get some exceptions in logs though—actually, one stacktrace in two variants:

In `ensime-langserver.log`:
```
[2017-10-10 22:40:20,204] ERROR akka.actor.OneForOneStrategy - null
java.lang.NullPointerException: null
	at com.orientechnologies.orient.core.index.sbtree.local.OSBTree.findBucket(OSBTree.java:1765)
	at com.orientechnologies.orient.core.index.sbtree.local.OSBTree.get(OSBTree.java:200)
	at com.orientechnologies.orient.core.index.engine.OSBTreeIndexEngine.get(OSBTreeIndexEngine.java:128)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doGetIndexValue(OAbstractPaginatedStorage.java:2123)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.getIndexValue(OAbstractPaginatedStorage.java:2105)
	at com.orientechnologies.orient.core.index.OIndexOneValue.get(OIndexOneValue.java:58)
	at com.orientechnologies.orient.core.index.OIndexOneValue.get(OIndexOneValue.java:40)
	at com.orientechnologies.orient.core.index.OIndexAbstractDelegate.get(OIndexAbstractDelegate.java:58)
	at com.orientechnologies.orient.core.index.OIndexTxAwareOneValue.get(OIndexTxAwareOneValue.java:262)
	at com.orientechnologies.orient.core.index.OIndexTxAwareOneValue.get(OIndexTxAwareOneValue.java:40)
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.getVertices(OrientBaseGraph.java:834)
	at org.ensime.indexer.orientdb.syntax.package$RichGraph$.readUniqueV(SimpleOrient.scala:211)
	at org.ensime.indexer.graph.GraphService.$anonfun$find$4(GraphService.scala:327)
	at scala.collection.immutable.List.flatMap(List.scala:335)
	at org.ensime.indexer.graph.GraphService.$anonfun$find$3(GraphService.scala:326)
	at org.ensime.indexer.orientdb.syntax.package$.withGraph(SimpleOrient.scala:165)
	at org.ensime.indexer.orientdb.syntax.package$.$anonfun$withGraphAsync$2(SimpleOrient.scala:176)
	at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
	at scala.concurrent.package$.blocking(package.scala:142)
	at org.ensime.indexer.orientdb.syntax.package$.$anonfun$withGraphAsync$1(SimpleOrient.scala:176)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:653)
	at scala.util.Success.$anonfun$map$1(Try.scala:251)
	at scala.util.Success.map(Try.scala:209)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:287)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

In `pc.stdout.log`:
```
Oct 10, 2017 10:45:48 PM com.orientechnologies.common.log.OLogManager log
SEVERE: $ANSI{green {db=graph-2.0.4}} Exception `2950C84E` in storage `graph-2.0.4`
java.lang.NullPointerException
	at com.orientechnologies.orient.core.index.sbtree.local.OSBTree.findBucket(OSBTree.java:1765)
	at com.orientechnologies.orient.core.index.sbtree.local.OSBTree.get(OSBTree.java:200)
	at com.orientechnologies.orient.core.index.engine.OSBTreeIndexEngine.get(OSBTreeIndexEngine.java:128)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.doGetIndexValue(OAbstractPaginatedStorage.java:2123)
	at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.getIndexValue(OAbstractPaginatedStorage.java:2105)
	at com.orientechnologies.orient.core.index.OIndexOneValue.get(OIndexOneValue.java:58)
	at com.orientechnologies.orient.core.index.OIndexOneValue.get(OIndexOneValue.java:40)
	at com.orientechnologies.orient.core.index.OIndexAbstractDelegate.get(OIndexAbstractDelegate.java:58)
	at com.orientechnologies.orient.core.index.OIndexTxAwareOneValue.get(OIndexTxAwareOneValue.java:262)
	at com.orientechnologies.orient.core.index.OIndexTxAwareOneValue.get(OIndexTxAwareOneValue.java:40)
	at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.getVertices(OrientBaseGraph.java:834)
	at org.ensime.indexer.orientdb.syntax.package$RichGraph$.readUniqueV(SimpleOrient.scala:211)
	at org.ensime.indexer.orientdb.syntax.package$RichGraph$.upsertV(SimpleOrient.scala:233)
	at org.ensime.indexer.graph.GraphService.$anonfun$persist$2(GraphService.scala:238)
	at org.ensime.indexer.graph.GraphService.$anonfun$persist$2$adapted(GraphService.scala:223)
	at scala.collection.immutable.List.foreach(List.scala:389)
	at org.ensime.indexer.graph.GraphService.$anonfun$persist$1(GraphService.scala:223)
	at org.ensime.indexer.graph.GraphService.$anonfun$persist$1$adapted(GraphService.scala:218)
	at org.ensime.indexer.orientdb.syntax.package$.withGraph(SimpleOrient.scala:165)
	at org.ensime.indexer.orientdb.syntax.package$.$anonfun$withGraphAsync$2(SimpleOrient.scala:176)
	at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
	at scala.concurrent.package$.blocking(package.scala:142)
	at org.ensime.indexer.orientdb.syntax.package$.$anonfun$withGraphAsync$1(SimpleOrient.scala:176)
	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:653)
	at scala.util.Success.$anonfun$map$1(Try.scala:251)
	at scala.util.Success.map(Try.scala:209)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:287)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by dragos** [comment]
That seems to be an issue with OrientDB, a dependency of Ensime. Can you try to delete the `.ensime_cache` directory?

**Comment by Blaisorblade** [comment]
Oh, this time removing the cache fixed everything! (Done it already for a previous issue). "Change All occurrences" is still string-based, but that's not documented as working. So maybe this is just working?

**Comment by dragos** [comment]
No, I don't think that's implemented. So whatever it is, it is VS Code's default.

**Comment by Blaisorblade** [comment]
Good—can this be closed then or is Scala 2.12 still somehow unsupported?

**Comment by dragos** [comment]
No, I think we should close this ticket.
